export const _analyzedResume_Basic ={
    "contactInfo": {
        "name": "ABIRAMI MUNI",
        "email": "muni1aby@gmail.com",
        "phone": "517-536-6384",
        "location": null,
        "linkedin": null,
        "portfolio": null,
        "github": null
    },
    "professionalSummary": "10+ years of experience as a Business Analyst with solid understanding of Business Requirement gathering, Business Process flow, Business Process Modelling, Data Analysis, Data Mapping, application upgrades, and Business Analysis.",
    "experience": [
        {
            "title": "Sr. Business System Analyst - Medicaid",
            "company": "Ecolab",
            "location": "St Paul MN",
            "startDate": "05/2023",
            "endDate": "Present",
            "duration": null,
            "responsibilities": [
                "Conducted troubleshooting of errors in production reports and worked extensively with Oracle and Teradata database stages in data warehousing development, achieving notable performance improvements.",
                "Identified and documented changes in HIPAA EDI transactions (837P, 835, 276/277, 270/271) by analyzing 4010A1 and 5010 TR3 implementation guides.",
                "Utilized best practices in PMO methodology to develop project plans tailored to stakeholder needs, ensuring successful project outcomes.",
                "Led MITA Business Process Modelling to ensure Medicaid operations were in line with CMS rules.",
                "Applied ICD-9 and ICD-10 coding standards in healthcare systems, focusing on inpatient, outpatient, and reimbursement methodologies within Medicare and Medicaid domains.",
                "Gained experience in claims processing and regulatory compliance for EDI/HIPAA implementation, providing expertise in insurance regulations and Medicaid.",
                "Created high-level test scenarios, test cases, and scripts based on Data Hub requirements as outlined in RSDs and DSDs, adhering to HIPAA compliance guidelines.",
                "Addressed and resolved file transmission issues, assisting customers with Medicaid insurance claim inquiries, and interpreting X12 implementation guides for transactions like 837P, 837I, and 837D.",
                "Scheduled and distributed reports using Cognos Connection and performed performance tuning by analyzing SQL and Cognos turnaround times.",
                "Gathered and documented business needs for enhancing Medicaid Management Information Systems (MMIS).",
                "Gathered business requirements for ICD-10 groupings and maintenance processes, including ICD-10 business rules remediation and Medical Claims Processing Systems (MCPS).",
                "Delivered EDI interfaces with commercial and government payers, including Medicare and Medicaid, ensuring smooth transactions and compliance.",
                "Analyzed and integrated ICD-9-CM and ICD-9-PCS with ICD-10-CM and ICD-10-PCS using the GEM's tool for effective mapping and transition.",
                "Provided healthcare services to business clients, assisting with Affordable Care Act applications and regulations.",
                "Analyzed and tested workflows for integrating clinical records, pharmacy data, and clinical guidelines while ensuring compliance with HIPAA EDI-X12 standards (4010/5010).",
                "Leveraged expertise in subprime mortgages and related concepts, such as debt-service coverage ratio and loan-to-value ratio (LTV), to enhance the insurance market."
            ],
            "achievements": [],
            "keywords": [
                "Medicaid",
                "HIPAA",
                "EDI",
                "PMO",
                "ICD-9",
                "ICD-10",
                "CMS",
                "MMIS",
                "MCPS",
                "Data Warehousing",
                "Oracle",
                "Teradata",
                "Cognos",
                "SQL"
            ]
        },
        {
            "title": "Sr. Salesforce Business Analyst",
            "company": "Cummins",
            "location": "Columbus, Indiana",
            "startDate": "09/2021",
            "endDate": "04/2023",
            "duration": null,
            "responsibilities": [
                "Designed and maintained Apex classes, triggers, batch classes, and Visualforce pages, ensuring seamless customization and automation on the Salesforce.com platform.",
                "Supported sales teams by optimizing lead conversion, tracking opportunities, managing accounts, and automating custom quote generation, including approval processes and discount matrices with validation rules.",
                "Configured Salesforce CRM solutions based on detailed design documents, including custom objects, workflows, record types, reports, dashboards, and page layouts to align with business requirements.",
                "Reviewed and analyzed documentation, such as BRD, FSD, RTM, and SRS, ensuring that all technical and business requirements were clearly articulated and adhered to.",
                "Integrated Salesforce.com with external systems using SOAP and REST API, while also leveraging AppExchange apps like ExactTarget and Dream Factory for campaign management.",
                "Customized Salesforce Service Cloud functionality, including Case Management, Live Agent, Knowledge Base, Communities, Profiles, and Permission Sets, while ensuring adherence to organization-wide defaults.",
                "Proficiently utilized Sales Cloud, Service Cloud, and other Salesforce tools like Chatter Collaboration and AppExchange applications to improve business processes.",
                "Built detailed training materials and user guides for both standard and custom applications in Salesforce and marketing automation tools like Eloqua.",
                "Participated in vendor evaluations and supported the integration of Salesforce with Eloqua, ensuring efficient marketing automation and lead generation processes.",
                "Configured Salesforce CRM for efficient management of Accounts, Leads, Contacts, Campaigns, Opportunities, Forecasts, Dashboards, and Reports.",
                "Implemented Pardot functionalities such as email templates, landing pages, prospect tracking, and lead nurturing to enhance marketing campaigns.",
                "Managed Salesforce processes related to Opportunity Management, Lead Management, and Case Management, ensuring alignment with business workflows.",
                "Worked with SOQL and SOSL queries while adhering to Governor Limits for seamless data manipulation within the Salesforce database.",
                "Implemented Apttus CPQ (Configure, Price, Quote) for streamlining and automating the quoting process on the Sales Cloud platform.",
                "Enhanced email campaigns by utilizing custom Pardot forms integrated with the organization's web platform for better engagement.",
                "Collaborated with Salesforce Premium Support teams for issue resolution and advanced troubleshooting.",
                "Performed exception handling and created custom error messages to provide user-friendly experiences on Visualforce pages.",
                "Developed and tested Visualforce pages using standard, custom, and extension controllers to meet unique business requirements.",
                "Conducted performance analysis and evaluated Force.com PaaS to recommend its suitability for business needs.",
                "Implemented integrated campaign management through tools like ExactTarget and Dream Factory, improving marketing efficiency.",
                "Supported Sales Cloud functionality with solutions such as email notifications for deal stages, discount approval workflows, and validation rules.",
                "Worked extensively on Software Development Life Cycle (SDLC) documentation, including use cases, functional specifications, and testing artifacts."
            ],
            "achievements": [],
            "keywords": [
                "Salesforce",
                "Apex",
                "Visualforce",
                "CRM",
                "SOAP",
                "REST API",
                "AppExchange",
                "Service Cloud",
                "Sales Cloud",
                "Pardot",
                "Eloqua",
                "SOQL",
                "SOSL",
                "Apttus CPQ",
                "SDLC"
            ]
        },
        {
            "title": "Sr. Guidewire Policy Centre Business System Analyst",
            "company": "UBS",
            "location": "weehawken, NJ",
            "startDate": "12/2018",
            "endDate": "08/2021",
            "duration": null,
            "responsibilities": [
                "Facilitated Joint Requirement Planning (JRP) sessions with problem-solving skills in understanding the Requirements pertaining to Loan Origination to Loan Processing.",
                "Gathered requirements by conducting meetings and brainstorming sessions with end users and SME and document them using Requisite Pro - the documentation tool offered by Rational.",
                "Led the full-cycle installation of Guidewire products (PolicyCenter, ClaimCenter, and BillingCenter) for Property & Casualty (P&C) insurance clients, ensuring compliance with business goals and regulatory requirements.",
                "Introduced Agile and RUP methodologies to reflect liquid nature of front-office improving time-to-market",
                "Facilitated requirements gathering sessions for KYC system upgrades, enabling better customer identification, risk assessment, and due diligence.",
                "Establish documentation for agile methodology for implementation with a very water-fall-centric development team.",
                "Analyzed User Requirement Document, Business Requirement Document (BRD), Technical Requirement Specification and Functional Requirement Specification (FRS).",
                "Collaborated with business users and software development team within AGILE framework to ensure rapid and successful implementation of the solution",
                "Utilized Agile SCRUM methodology to develop User Stories, Product Backlog, and Sprint Backlog.",
                "Collaborated closely with business stakeholders and subject matter experts (SMEs) to finalize requirements through review sessions and gain formal sign-offs from business owners.",
                "Participated actively in Sprint Planning and Sprint Retrospective meetings to ensure alignment with Agile project goals and timelines.",
                "Engaged with technical teams to identify and document both functional and non-functional requirements, ensuring a comprehensive understanding of system needs.",
                "Worked alongside product owners and business users to pinpoint data model discrepancies, document domain-specific details, and refine requirements.",
                "Gathered detailed requirements for critical application features such as Policy Information, Property Details, Coverage Screens, and Quote Summary Screens.",
                "Contributed to the documentation and understanding of Policy Life Cycle workflows, including processes like Submission, Renewal, Cancellation, Reinstatement, Rewrite, and Policy Changes.",
                "Conducted detailed discussions with SMEs and product owners to clarify business needs and ensure accurate documentation of requirements.",
                "Worked as a User/Customer advocate and negotiated with user as well as with developers and management staff to resolve any requirement conflict to bridge the Gaps between IT and Business."
            ],
            "achievements": [],
            "keywords": [
                "Guidewire",
                "PolicyCenter",
                "ClaimCenter",
                "BillingCenter",
                "Agile",
                "RUP",
                "KYC",
                "JRP",
                "BRD",
                "FRS",
                "SCRUM",
                "User Stories",
                "Product Backlog",
                "Sprint Backlog"
            ]
        },
        {
            "title": "Business Analyst",
            "company": "Ceequence Technologies",
            "location": "Hyderabad, India",
            "startDate": "02/2017",
            "endDate": "09/2018",
            "duration": null,
            "responsibilities": [
                "As a business analyst, responsible for Requirements gathering from various insurance companies to develop a system to check for the outstanding balance from various accounts using the highly efficient Waterfall methodology of software development.",
                "Developed training material and trained the users on newly developed applications.",
                "Analyzed and wrote technical documentation for risk analysis on customer support issues.",
                "Ensured that all system additions and changes complied with healthcare industry requirements such as HIPAA, CMS, and state guidelines. Regularly collaborated with compliance teams to guarantee contract adherence.",
                "Extensively worked in creating Test Procedures, Test plans and Test Case for User acceptance testing (UAT).",
                "Experienced in Quality Centre for Tracking defects and interacting with team members in fixing errors",
                "Prepared and presented monthly collection reports.",
                "Managed the medical record retrieval process for risk adjustment programs, collaborating with healthcare providers to guarantee correct data gathering and reporting."
            ],
            "achievements": [],
            "keywords": [
                "Waterfall",
                "HIPAA",
                "CMS",
                "UAT",
                "Quality Centre",
                "Risk Adjustment"
            ]
        },
        {
            "title": "Jr. Business Analyst",
            "company": "Avon Technologies Pvt Ltd",
            "location": "Hyd India",
            "startDate": "10/2014",
            "endDate": "01/2017",
            "duration": null,
            "responsibilities": [
                "Worked closely with the Product Owner in defining the product road map and capabilities for enhancements to the enterprise claims management application",
                "Actively participates and drove continuous improvement for process and productivity to improve overall customer satisfaction and delivery of the services, meeting the requirements of the product",
                "Continually verified requirements individually and collectively through the project lifecycles, writing formal specifications, process workflows, communicating such documentation with stakeholders and technology teams.",
                "Created work breakdown structures (WBS), allocations, and daily status reports to ensure effective development in an Robust agile setting.",
                "Worked closely with the Product Owner in designing and implementing a more accurate, efficient and productive process of capturing the business requirements in the form of user stories",
                "Assisted the Scrum Master in facilitating Scrum Ceremonies like Daily Standup, Spring Review, Planning and Retrospective"
            ],
            "achievements": [],
            "keywords": [
                "Agile",
                "Scrum",
                "Product Owner",
                "User Stories",
                "WBS"
            ]
        }
    ],
    "skills": {
        "technical": [
            "SQL",
            "Swagger",
            "Postman",
            "TestLink",
            "JIRA",
            "MS-Project",
            "Team Foundation Server",
            "Liquid Planner",
            "SharePoint",
            "Confluence",
            "SQL Server",
            "Netezza",
            "Teradata",
            "MS SQL Server",
            "Salesforce",
            "Apex",
            "Visualforce",
            "SOAP",
            "REST API",
            "AppExchange",
            "Pardot",
            "Eloqua",
            "SOQL",
            "SOSL",
            "Apttus CPQ",
            "Guidewire",
            "PolicyCenter",
            "ClaimCenter",
            "BillingCenter",
            "Requisite Pro",
            "Rational Rose",
            "Quality Centre",
            "IBM Cognos Report Studio",
            "PL-SQL",
            "SSIS",
            "SSRS",
            "ETL Informatica",
            "JavaScript",
            "Java",
            "HTML",
            "Python",
            "Tableau",
            "Power BI",
            "SAS",
            "EPIC",
            "QlikView",
            "EDI Translator Tools",
            "MS Visio",
            "R",
            "JSON",
            "Azure",
            "HP QC",
            "RUP",
            "UML",
            "SWOT analysis",
            "GAP Analysis",
            "Cognos Powerplay Transformer v8.4",
            "Mainframes",
            "JCL",
            "Db2",
            "Oracle",
            "Load Runner",
            "WinRunner",
            "Share gate",
            "Planview",
            "Azure DevOps",
            "Microsoft CRM 3.0",
            "Gantt project / Gantt chart"
        ],
        "soft": [
            "Communication",
            "Leadership",
            "Problem-solving",
            "Critical thinking",
            "Collaboration",
            "Requirement gathering",
            "Business Process Modelling",
            "Data Analysis",
            "Data Mapping",
            "Project Management"
        ],
        "certifications": [],
        "languages": [],
        "categories": {
            "Programming": [
                "Apex",
                "Visualforce",
                "JavaScript",
                "Java",
                "HTML",
                "Python",
                "PL-SQL"
            ],
            "Databases": [
                "SQL",
                "SQL Server",
                "Netezza",
                "Teradata",
                "MS SQL Server",
                "Db2",
                "Oracle"
            ],
            "Cloud": [
                "Salesforce",
                "Azure"
            ],
            "Project Management": [
                "MS-Project",
                "Team Foundation Server",
                "Liquid Planner",
                "Planview",
                "Azure DevOps",
                "Gantt project / Gantt chart"
            ],
            "Business Analysis": [
                "JIRA",
                "Confluence",
                "SharePoint",
                "Requisite Pro",
                "Rational Rose"
            ],
            "Data Analysis & Visualization": [
                "Tableau",
                "Power BI",
                "SAS",
                "QlikView",
                "IBM Cognos Report Studio",
                "Cognos Powerplay Transformer v8.4"
            ],
            "ETL": [
                "SSIS",
                "SSRS",
                "ETL Informatica"
            ],
            "Testing": [
                "Swagger",
                "Postman",
                "TestLink",
                "HP QC",
                "Load Runner",
                "WinRunner"
            ],
            "Other": [
                "EPIC",
                "EDI Translator Tools",
                "MS Visio",
                "R",
                "JSON",
                "RUP",
                "UML",
                "SWOT analysis",
                "GAP Analysis",
                "Mainframes",
                "JCL",
                "Microsoft CRM 3.0",
                "Share gate"
            ]
        }
    },
    "education": [
        {
            "institution": "CMR Engineering college",
            "degree": "Bachelors",
            "field": "ECE",
            "location": "India",
            "graduationDate": 2015,
            "gpa": null,
            "honors": null,
            "relevantCourses": []
        }
    ],
    "projects": [],
    "certifications": [],
    "atsAnalysis": {
        "keywordDensity": "high",
        "formatCompatibility": "moderate",
        "potentialIssues": [
            "Length (over two pages)",
            "Dense formatting",
            "Repetitive information"
        ],
        "missingElements": [
            "Quantifiable achievements",
            "Location in contact info"
        ],
        "strengths": [
            "Clear job titles",
            "Keyword-rich content",
            "Technical skills listed"
        ]
    },
    "keyPhrases": [
        "10+ years of experience as a Business Analyst",
        "Led UAT for new Medicaid system implementations",
        "Ensuring alignment with MITA standards",
        "Facilitated communication between Guidewire developers and business stakeholders",
        "Implemented SQL scripts, stored procedures, triggers and indexes",
        "Deep technical background and solid working knowledge of SQL Server Data warehouse systems",
        "Collaborated with IT and security teams to identify and document business needs for risk management",
        "Agile/Scrum and Waterfall Methodologies for Software Development Life Cycle",
        "Created AS-IS and TO-BE business process flow diagrams",
        "Collaborated with data engineers and architects to ensure data accuracy, consistency, and accessibility"
    ],
    "recommendedJobTitles": [
        "Senior Business Analyst",
        "Salesforce Business Analyst",
        "Guidewire Business Analyst",
        "Healthcare IT Business Analyst",
        "Data Analyst"
    ],
    "careerLevel": "Senior",
    "industrySectors": [
        "Healthcare",
        "Insurance",
        "Information Technology"
    ]
}