export const _analyzeJob = {
  title: "Cloud Software Engineer",
  targetRole: "Software Engineer",
  seniority: "Mid-Level",
  company: "IBM",
  location: null,
  keyRequirements: [
    "Bachelor's degree in Computer Science, Software Engineering or equivalent",
    "1+ year experience in Agile environment using Scrum or Kanban",
    "1+ year of development experience with Java, Node.js, Golang, NoSQL, SQL, Redis, etc.",
    "1+ year experience building and operating distributed cloud services (IBM Cloud, AWS, Azure, etc.)",
    "1+ year experience with web technologies (HTTP, REST, JSON, HTML, JavaScript)",
    "Understanding of microservice architecture and cloud programming practices",
    "Strong API design skills",
    "Continuous learning and mentoring aptitude",
  ],
  keywords: {
    mustHave: [
      "Cloud",
      "Software Engineer",
      "Agile",
      "Java",
      "Node.js",
      "Golang",
      "NoSQL",
      "SQL",
      "Redis",
      "DevSecOps",
      "CI/CD",
      "Docker",
      "Kubernetes",
      "Microservices",
      "API",
    ],
    niceToHave: [
      "Cloudant",
      "Istio",
      "AWS",
      "Azure",
      "SRE",
      "Container Orchestration",
      "Performance Testing",
    ],
    buzzwords: [
      "Industry-leading",
      "Innovative",
      "Dynamic",
      "Highly-available",
      "Scalable",
      "World-class",
      "Modern",
      "Cutting-edge",
    ],
  },
  requiredSkills: {
    technical: [
      "Java",
      "Node.js",
      "Express.js",
      "Golang",
      "NoSQL",
      "SQL",
      "Redis",
      "Distributed Caches",
      "HTTP",
      "REST",
      "JSON",
      "HTML",
      "JavaScript",
      "Docker",
      "Kubernetes",
      "Istio",
    ],
    domain: ["Cloud Computing", "Security"],
    tools: ["Cloudant", "Redis", "Docker", "Kubernetes", "Istio"],
  },
  preferredSkills: {
    technical: ["React", "Angular"],
    domain: ["Cybersecurity", "Identity and Access Management"],
    tools: [],
  },
  experience: {
    yearsRequired: 1,
    yearsPreferred: null,
    specificRequirements: [
      "Building and operating highly secured, distributed cloud services",
      "Working in Agile environment using Scrum or Kanban methodologies",
      "Developing applications with Java, Node.js, Golang, NoSQL DB, SQL, Redis, etc.",
      "Building and operating distributed cloud services with IBM Cloud, AWS, Azure, etc.",
      "Experience with web technologies: HTTP, REST, JSON, HTML, JavaScript, etc.",
      "Remotely supporting customer engagements",
    ],
  },
  education: {
    degree: "Bachelor's",
    field: "Computer Science, Software Engineering or equivalent",
    isRequired: true,
  },
  responsibilities: [
    "Design and implement IBM Cloud Platform Services",
    "Develop highly-available, distributed cloud services",
    "Convert open specifications/RFCs to design docs and implementation",
    "Improve existing tools, frameworks, and DevSecOps workflows",
    "Document and share experience, mentor team members",
  ],
  atsKeywords: [
    "Cloud",
    "Software Engineer",
    "IBM Cloud",
    "AWS",
    "Azure",
    "Java",
    "Node.js",
    "Golang",
    "NoSQL",
    "SQL",
    "Redis",
    "Docker",
    "Kubernetes",
    "Istio",
    "DevSecOps",
    "CI/CD",
    "Agile",
    "Scrum",
    "Kanban",
    "Microservices",
    "API",
    "Security",
  ],
  keyPhrases: [
    "Developing highly-available, distributed cloud services",
    "Building and operating highly secured, distributed cloud services",
    "Experience in security or identity and access management",
    "Understanding of microservice architecture and modern cloud programming practices",
    "Strong ability to design a clean, developer-friendly API",
    "Passionate about constant, continuous learning and applying new technologies",
    "Keen troubleshooting skills and strong verbal/written communication skills",
  ],
  formatRecommendations: [
    "Use keywords throughout your resume",
    "Quantify accomplishments with metrics and numbers",
    "Tailor your resume to the specific job description",
    "Use a clear and concise format with consistent formatting",
  ],
  avoidPhrases: [
    "Extensive experience",
    "Team player",
    "Results-oriented",
    "Hard worker",
    "Proactive",
  ],
};
