export const _analyzedResume_Basic = {
  contactInfo: {
    name: "Vinay M",
    email: "vinayr0409@gmail.com",
    phone: "469-251-5257",
    location: null,
    linkedin: "Not Available",
    portfolio: null,
    github: null,
  },
  summaries: [
    {
      type: "summary",
      heading: "Summary: ",
      content:
        "A driven and goal-oriented Full Stack Developer, I bring Around 6 years of expertise in Java and J2EE technologies analysis, development, testing, and implementation of Web-based, client/server, enterprise, and distributed applications throughout the whole Software Development Life Cycle (SDLC). My comprehensive grasp of the software development life cycle, coupled with an acute awareness of client exigencies and business imperatives, underscores my proficiency. I excel not only in technical prowess but also in fostering robust communication channels and collaborative environments, facilitating seamless project delivery. Continuously striving for innovation, I possess an insatiable appetite for learning and integrating emerging technologies into my repertoire.",
      format: "paragraph",
    },
    {
      type: "technical_summary",
      heading: "Technical Summary: ",
      content:
        ' Practical experience using Lambda expressions and streams in Java 8, which leads to the construction of code using a declarative approach.\n Proficiency in developing online applications utilising a range of Spring Framework functionalities, including Spring IOC, Spring MVC, Spring AOP, Spring Batch, Spring Boot, and Spring Security.\n Knowledge of Spring MVC Controllers, Spring Boot, Validators, Spring Annotations, Spring Tag Library, Application Context Configuration, Inversion of Control (IOC), Spring LDAP, Spring Batch, Spring Scheduler, Spring Aspect Orientated Programming (AOP), Spring DAO, Hibernate, and Spring Security, as well as Hibernate as the back end ORM tool for persistence layer implementation and POJO mapping."\n Skilled in using Hibernate for Object-Relational Mapping (ORM) to integrate and interact with databases. Also proficient  in  employing  Hibernate/JPA  to  map  Java  objects  to  database  tables, utilizing  HQL  for  query operations.\n Proficient in working with J2EE applications across various Integrated Development Environments (IDEs) such as Eclipse and NetBeans.\n Knowledgeable  about  developing  websites  with  HTML5, CSS3, JavaScript, AJAX, jQuery, and  Angular.JS technologies.\n Proficient in utilizing Grunt task runner and managing library installations through Bower in a Node.js environment.\n Skilled in working with a range of XML technologies such as XPath, XQuery, XSLT, XSD, SAX, DOM, and JAXB.\n Experienced in applying MVC architecture and implementing J2EE Design Patterns like Singleton, Session Facade, Service Locator, DAO, DTO, and Business Delegate in the development of enterprise web applications.\n Strong in Core Java concepts including OOPs, Collections, Exception Handling, I/O Systems, Swing, Annotations, Multi-threading, Lambda Expressions, and Generics.\n Expertise in Docker Engine and Docker Machine for deploying scalable, microservices-based applications.\n Proficient in AWS services including EC2, S3, Simple DB, RDS, Elastic Load Balancing, SQS, IAM, CloudWatch, EBS, and CloudFront.\n Experienced in deploying applications across JBoss, IBM WebSphere, Oracle WebLogic, and Apache Tomcat servers.\n Adept in developing SOAP and RESTful web services using Jersey, Spring, and CXF, with extensive experience in JSON, JAXB, JAXP, and REST frameworks.\n Proficient in working with NoSQL databases such as MongoDB to handle large datasets.\n Well-versed in SQL, PL/SQL, T-SQL, and managing views, functions, stored procedures, and triggers.\n Familiar with Agile SCRUM methodologies and pair programming. Strong interpersonal, communication, and analytical abilities; eager to work both alone and as a team member.',
      format: "bullets",
    },
  ],
  experience: [
    {
      title: "Full Stack Developer",
      company: "First Command",
      location: "Fort Worth, Texas",
      startDate: "07/2023",
      endDate: "Present",
      duration: null,
      description:
        "Client: First Command, Fort Worth, Texas. Role: Full Stack Developer\nThe project involved designing, developing, and supporting a cloud-based microservices application using Java 8, Spring Boot, and Spring MVC. The backend utilized REST APIs, Apache Kafka for messaging, and MongoDB for data persistence, while the frontend was built with React.js, Redux, and Node.js for a responsive and dynamic interface. Hosted on AWS, the application was developed using Agile methodologies, with continuous integration managed via Jenkins. Log4j and JUnit were used for logging and testing, ensuring a reliable, scalable, and high-performing solution.",
      environment:
        "Java 8, Spring Framework, Spring MVC, Spring Boot, Micro Services, REST, Apache Kafka, MongoDB, React.JS, Redux, Node.js, HTML5, CSS3, JavaScript, jQuery, AWS, Docker, Jenkins, Log4j, JUnit, Eclipse IDE, Agile, SCRUM, XML, SAX, DOM, Git",
      responsibilities: [
        "Involved in the Design, Development, and Support Stages of the Software Development Life Cycle (SDLC).",
        "Used Spring MVC framework to create a monolithic architecture.",
        "Involved in building action classes and beans for different modules using Spring MVC.",
        "Implemented a microservice architecture with Spring Boot-based services interacting over REST and Apache Kafka message brokers.",
        "Developed cloud microservices and used Spring Boot for backend implementation.",
        "Involved in creating MongoDB topics, partitions, and custom practitioner classes.",
        "Worked with microservice architecture using Spring Boot to modularize code and develop Rest APIs using Spring Rest.",
        "The application modules were coded, debugged, and tested using the Eclipse IDE.",
        "Involved in rendering extra components with custom HTML elements in React.js.",
        "Worked on MongoDB topics, partitions, and custom practitioner classes.",
        "Closely worked with applications that used React.JS and Node.js frameworks, NPM, and gulp folders to build the appropriate view, and redux to correctly root the URLs.",
        "worked on column filters for a data table using jQuery and React.JS.",
        "Making updates to current web apps and developing new components with React.JS.",
        "React.JS is used to update existing web applications and create new components.",
        "Developed XML files, schemas, and parsed them using SAX and DOM parsers.",
        "Worked with Java Messaging Services (JMS) to create messaging services.",
        "REACT.JS Virtual DOM is utilized for client-side view rendering and React-Redux for state management.",
        "worked with microservice architecture and Spring Boot to modularize code and construct Rest APIs with Spring Rest.",
        "Developed the front end, which includes a complex web interface built using HTML5, CSS3, React.JS, and Bootstrap for responsive design.",
        "Participated in SCRUM sessions and used the AGILE approach.",
        "Configured centralized logging using Elastic Search, Logstash, and Kibana.",
        "Log4j was used to log multiple levels of information into log files, including error, information, and debug.",
        "Create and maintain accessibility documentation, such as VPATs and accessibility statements, to communicate compliance efforts to stakeholders and customers.",
        "Implement and manage user-centered testing strategies, including screen reader (JAWS, NVDA) and keyboard navigation testing, to validate accessibility for all users.",
        "Set up the continuous integration (CI) workflow for the application with Jenkins.",
        "Involved in building and deploying a wide range of applications that use practically the whole AWS stack (including EC2, Route53, S3, RDS, Dynamo DB, SNS, SQS, and IAM), with an emphasis on high availability, fault tolerance, and auto-scaling in AWSCloudFormation.",
        "Spring was used to create microservices, and the application was tested with Spring Boot.",
      ],
      achievements: [],
      keywords: [
        "Java",
        "Spring",
        "Spring Boot",
        "Microservices",
        "REST",
        "Kafka",
        "MongoDB",
        "React.js",
        "AWS",
        "Docker",
        "Jenkins",
        "Agile",
      ],
    },
    {
      title: "Java Developer",
      company: "Lennar",
      location: "Miami, Florida",
      startDate: "01/2023",
      endDate: "06/2023",
      duration: null,
      description:
        "Client: Lennar, Miami, Florida. Role: Java Developer\nThe project focused on developing and maintaining a real estate management platform that streamlined property sales, mortgage processing, and customer relationship management. The application was built using Java and Spring technologies for the backend, with a responsive front-end developed in React.js. The system integrated with multiple third-party services including payment processors, credit agencies, and document management systems to provide a complete solution for real estate transactions.",
      environment:
        "Java 8, Spring Framework, Spring Boot, Hibernate, REST APIs, JPA, MySQL, Oracle, Git, Maven, Jenkins, React.js, Redux, JavaScript, HTML5, CSS3, Agile, JIRA, JUnit, Mockito, IntelliJ IDEA",
      responsibilities: [
        "Participated in development of Java code and complex SQL queries with stored procedures for a project that involved CRUD operations on Oracle in a Windows environment.",
        "Designed the front-end application using JavaScript frameworks.",
        "Contributed to Agile Software development.",
        "Proficient with a range of Spring modules, including Spring AOP.",
        "Improved code quality through unit testing with Junit 4.",
        "Connected to the MySQL database using the JDBC API.",
        "Built a REST API with Java Enterprise Edition (JEE), Spring, and Spring MVC.",
        "Implemented micro-service architecture using Spring Boot.",
        "Created RESTful web services in Java.",
        "Hibernate/JPA was used to map classes to MySQL tables.",
        "Used Git as the primary version control system, including creating and updating branches, submitting pull requests, and resolving conflicts from the command line.",
        "Used Maven for project building and used Jenkins for Continuous Integration/Continuous Deployment (CI/CD).",
        "Resolved critical bugs observed during quality assurance testing, as well as during the development phase.",
        "Implemented and expanded DAO and Repository design patterns using Hibernate and Spring Data.",
        "Modified Spring Java code to include configuration, annotation, and XML namespaces.",
        "Adapted the code to leverage Spring Boot, which provides an opinionated view on frameworks and third-party libraries.",
        "Conducted research on existing system functions for improvement and enhancement.",
        "Used core Java (J2SE/J2EE) and OOP methodologies to design complex structures.",
        "Used JavaScript to show hiding data, retrieve lost data, and data binding to display data without reloading the entire page.",
        "Developed Angular JS directives to automate HTML code generation based on data inputs, resulting in a more consistent user experience and fewer bugs.",
        "Angular JS was used to deploy applications efficiently.",
        "Utilized Hibernate technology for Object Relational Mapping (ORM) to maintain consistency across multiple database tiers, which increased data consistency and simplified development by 35%.",
        "Utilized Java 8's stream API for data processing, functional interfaces, and Lambda expressions.",
        "Scrum ceremonies were performed on a regular basis as part of the Agile methodology.",
        "Designed the front end with Angular, TypeScript, and CSS.",
        "Built RESTful Web services with Java, Spring MVC, and JSON.",
      ],
      achievements: [],
      keywords: [
        "Java 8",
        "Spring",
        "Spring Boot",
        "Hibernate",
        "REST",
        "JPA",
        "MySQL",
        "Oracle",
        "React.js",
        "Angular",
        "JavaScript",
        "Agile",
      ],
    },
    {
      title: "Java/J2EE Developer",
      company: "CGI Inc",
      location: "Hyderabad, India",
      startDate: "06/2019",
      endDate: "07/2022",
      duration: null,
      responsibilities: [
        "Participated in all phases of the software development lifecycle, including requirements analysis, system design, development, testing, and deployment of application enhancements.",
        "Extensive experience ensuring digital content meets ADA, WCAG 2.1, and Section 508 compliance requirements to create accessible user experiences for people with disabilities.",
        "Played a key role in analyzing requirements, designing modifications, and maintaining software components using Spring MVC.",
        "Developed RESTful web services using the Spring Boot framework, enabling faster and more efficient creation of cloud-based microservices.",
        "Employed Spring Boot's modular architecture to build and manage loosely coupled microservices, ensuring scalability and flexibility.",
        "Integrated Spring Boot with Hibernate to implement a robust persistence layer, leveraging JPA for seamless data storage and retrieval.",
        "Utilized Java Message Service (JMS) for asynchronous communication, ensuring reliable exchange of critical information across different application components.",
        "Built dynamic and responsive web applications using HTML5, CSS3, Bootstrap, and AngularJS.",
        "Extensively utilized AngularJS to create interactive and rich internet applications, enhancing user experience.",
        "Conduct thorough accessibility audits using tools like WAVE, Axe, and Lighthouse to identify non-compliant elements and provide remediation strategies to improve accessibility.",
        "Developed and managed Node.js streams for processing data from external sources, optimizing application performance.",
        "Worked with Enterprise Java Beans (EJB) to implement business logic, session management, and transaction handling, deploying these components on WebSphere Application Server.",
        "Used XML and JAXB to map Java classes to XML representations, facilitating seamless data exchange.",
        "Developed reusable and interoperable services using SOAP, WSDL, JAX-WS, and JAX-RPC web services.",
        "Collaborate with design, development, and content teams to integrate accessibility best practices, ensuring compliance from the initial design phase through final delivery.",
        "Designed and executed JUnit test cases to ensure high code quality and coverage.",
        "Employed Log4J for effective logging, error tracking, and debugging, leading to efficient problem resolution in web applications.",
        "Engaged in unit and integration testing, bug fixing, code reviews, and acceptance testing, contributing to a high-quality final product.",
        "Implemented the project within an Agile framework, specifically using the SCRUM iterative incremental model.",
        "Actively participated in sprint planning and execution, ensuring that project milestones were met and delivered on time.",
      ],
      achievements: [],
      keywords: [
        "J2EE",
        "Spring Framework",
        "Spring MVC",
        "Spring Boot",
        "Microservices",
        "Hibernate",
        "JMS",
        "HTML5",
        "CSS3",
        "Bootstrap",
        "AngularJS",
        "Node.js",
        "RESTful services",
        "EJB",
        "WebSphere",
        "XML",
        "JAXB",
        "SOAP",
        "JUnit",
        "Agile",
        "SCRUM",
      ],
    },
  ],
  skills: {
    technical: [
      "Java 11",
      "Java 8",
      "Java 7",
      "Java 6",
      "EJB",
      "Java Beans",
      "JSTL",
      "IMS",
      "JDBC",
      "JSP",
      "HTML5",
      "CSS3",
      "jQuery",
      "XPath",
      "AJAX",
      "XML",
      "Hibernate",
      "Spring",
      "Spring Boot",
      "AWS Code Deploy",
      "AWS Code Pipeline",
      "Flutter",
      "Jira",
      "Bugzilla",
      "Bootstrap",
      "React.js",
      "JavaScript",
      "React Native",
      "Node.js",
      "Redux",
      "Eclipse",
      "IBM WebSphere",
      "JBoss",
      "BEA Web Logic",
      "Apache Tomcat",
      "Oracle",
      "SQL Server",
      "DB2",
      "MySQL",
      "PL/SQL Developer",
      "Git",
      "SVN",
      "UNIX",
      "Linux",
      "Splunk",
      "Windows",
    ],
    soft: [
      "Communication",
      "Analytical Abilities",
      "Teamwork",
      "Interpersonal Skills",
    ],
    certifications: [],
    languages: [],
    categories: {},
  },
  education: [
    {
      institution: "Osmania University",
      degree: "Bachelor's",
      field: "Computer Science",
      location: null,
      graduationDate: "2020",
      gpa: null,
      honors: [],
      relevantCourses: [],
    },
    {
      institution: "Central Michigan University",
      degree: "Master's",
      field: "Information Technology",
      location: null,
      graduationDate: "2024",
      gpa: null,
      honors: [],
      relevantCourses: [],
    },
  ],
  projects: [],
  certifications: [],
  atsAnalysis: {
    keywordDensity: "high",
    formatCompatibility: "good",
    potentialIssues: [
      "Long summary sections",
      "Repetitive language",
      "Inconsistent formatting of skills section",
    ],
    missingElements: ["Quantifiable achievements", "Project portfolio/links"],
    strengths: [
      "Clear job titles",
      "Technical skills listed",
      "Experience section with responsibilities",
    ],
  },
  keyPhrases: [
    "Full Stack Developer",
    "Java/J2EE expertise",
    "Spring Boot/MVC",
    "Microservices architecture",
    "Cloud-based application development",
    "RESTful web services",
    "Agile/SCRUM methodologies",
    "Front-end development (React.js, AngularJS)",
    "Database management (SQL, NoSQL)",
    "AWS cloud infrastructure",
  ],
  recommendedJobTitles: [
    "Full Stack Developer",
    "Senior Java Developer",
    "Software Engineer",
    "Cloud Application Developer",
    "Microservices Architect",
  ],
  careerLevel: "Mid-Senior",
  industrySectors: [
    "Information Technology",
    "Software Development",
    "Cloud Computing",
  ],
};
