export const _optimize_resume = {
  contactInfo: {
    name: "Vinay M",
    email: "vinayr0409@gmail.com",
    phone: "469-251-5257",
    location: null,
    linkedin: "Not Available",
    portfolio: null,
    github: null,
  },
  summaries: [
    {
      type: "summary",
      heading: "Summary: ",
      content:
        "A driven Full Stack Developer with 6 years of experience in Java and J2EE technologies. I specialize in the analysis, development, testing, and implementation of web-based, client/server, enterprise, and distributed applications, following Agile methodologies throughout the SDLC. My expertise includes Spring Boot, microservices architecture, cloud platforms (AWS), and front-end technologies like React.js. I am proficient in building RESTful APIs, working with NoSQL and SQL databases, and utilizing Docker and Kubernetes for containerization. I am eager to contribute to a collaborative environment and continue learning emerging technologies.",
      format: "paragraph",
    },
    {
      type: "technical_summary",
      heading: "Technical Summary: ",
      content:
        " Expertise in Java 8+ utilizing Lambda expressions, streams, and functional interfaces.\n Proficient in developing cloud-based applications and REST APIs using Spring Boot and Spring MVC.\n Experience building and deploying microservices using Docker and Kubernetes.\n Skilled in front-end development using React.js, HTML5, CSS3, JavaScript, and associated technologies.\n Proficient with NoSQL databases (MongoDB) and SQL databases.\n Experienced with AWS cloud services (EC2, S3, RDS, etc.).\n Familiar with Agile SCRUM methodologies and CI/CD pipelines using Jenkins.\n Strong understanding of API design principles and implementation.\n Experience with Node.js and related frameworks.",
      format: "bullets",
    },
  ],
  experience: [
    {
      title: "Cloud Software Engineer",
      company: "First Command",
      location: "Fort Worth, Texas",
      startDate: "07/2023",
      endDate: "Present",
      duration: null,
      description:
        "The project involved designing, developing, and supporting a cloud-based microservices application using Java 8, Spring Boot, and Spring MVC. The backend utilized REST APIs, Apache Kafka for messaging, and MongoDB for data persistence, while the frontend was built with React.js, Redux, and Node.js for a responsive and dynamic interface. Hosted on AWS, the application was developed using Agile methodologies, with continuous integration managed via Jenkins. Log4j and JUnit were used for logging and testing, ensuring a reliable, scalable, and high-performing solution.",
      environment:
        "Java 8, Spring, MVC, Spring Boot, Micro Services, Hibernate, Docker, HTML5, CSS3, JavaScript, React.JS, REDUX, React Native, Node.JS, XML, JMS, REST, AWS, SOAP, EJB, Log4j, JUnit, Jenkins, MongoDB, PL/SQL, SQL, Agile, Windows",
      responsibilities: [
        "Designed, developed, and supported applications throughout the SDLC using Agile methodologies.",
        "Developed a microservice architecture using Spring Boot, REST APIs, and Apache Kafka message brokers.",
        "Built and deployed cloud microservices using Spring Boot and AWS.",
        "Created and managed MongoDB topics and partitions.",
        "Developed front-end components using React.js, HTML5, CSS3, and Bootstrap for responsive design.",
        "Implemented centralized logging using Elastic Search, Logstash, and Kibana.",
        "Configured CI/CD pipelines using Jenkins.",
        "Built and deployed applications using AWS services (EC2, S3, RDS, DynamoDB, etc.) with a focus on high availability and auto-scaling.",
      ],
      achievements: [],
      keywords: [
        "Java",
        "Spring Boot",
        "Spring MVC",
        "REST APIs",
        "Apache Kafka",
        "MongoDB",
        "React.js",
        "AWS",
        "Agile",
        "Jenkins",
        "Microservices",
        "Cloud",
        "Docker",
        "Kubernetes",
      ],
    },
    {
      title: "Cloud Software Engineer",
      company: "Lennar",
      location: "Miami, Florida",
      startDate: "01/2023",
      endDate: "06/2023",
      duration: null,
      description:
        "Worked on modernizing legacy applications by migrating them to a cloud-based microservices architecture. The project focused on improving scalability, reliability, and maintainability while reducing operational costs. The solution involved containerization with Docker, orchestration with Kubernetes, and implementation of CI/CD pipelines for automated testing and deployment.",
      environment:
        "Java 8, Spring Boot, React.js, Docker, AWS, Hibernate, Node.js, MongoDB, Agile Scrum, TDD, Jenkins, Microservices, Cloud, Kubernetes, Git, Maven, REST APIs",
      responsibilities: [
        "Participated in all phases of the SDLC, from requirements gathering to deployment.",
        "Developed cloud-hosted web applications and REST APIs using Spring Boot and Tomcat.",
        "Designed and developed microservices using Spring Boot and deployed them to the cloud.",
        "Built custom Docker images and integrated them with Spring Boot.",
        "Developed the Data Access Layer using Hibernate and the DAO Design Pattern.",
        "Developed front-end components using React.js and managed state with Redux.",
        "Worked with Node.js to build directives, services, controllers, and filters.",
        "Managed AWS services (EC2, S3, ELB, Auto-Scaling, etc.) using the AWS Console and API integration.",
        "Used Agile Scrum methodology and TDD.",
      ],
      achievements: [],
      keywords: [
        "Java 8",
        "Spring Boot",
        "React.js",
        "Docker",
        "AWS",
        "Hibernate",
        "Node.js",
        "MongoDB",
        "Agile Scrum",
        "TDD",
        "Jenkins",
        "Microservices",
        "Cloud",
      ],
    },
    {
      title: "Java/J2EE Developer",
      company: "CGI Inc",
      location: "Dallas, Texas",
      startDate: "07/2021",
      endDate: "12/2022",
      duration: null,
      description:
        "Led the development of a financial services portal that integrated multiple backend systems into a unified customer experience. The project included implementing secure authentication, real-time transaction processing, and a responsive UI designed for both desktop and mobile users. The solution improved customer satisfaction rates and reduced call center volume by enabling self-service.",
      environment:
        "Java, J2EE, Spring Boot, Spring MVC, Hibernate, REST APIs, Swagger, Oracle, MongoDB, React.js, Redux, JavaScript, HTML5, CSS3, Bootstrap, Agile, Jenkins, Maven, Git, JUnit, Mockito",
      responsibilities: [
        "Designed and developed secure enterprise applications using Spring Boot, Spring MVC, and Hibernate.",
        "Developed RESTful services for a microservices architecture.",
        "Implemented OAuth2 authentication and JWT tokens for secure API access.",
        "Worked on complex SQL queries and stored procedures.",
        "Created front-end components using React.js and Redux.",
        "Performed code reviews and mentored junior developers.",
        "Participated in Agile ceremonies and implemented Continuous Integration using Jenkins.",
        "Created unit and integration tests using JUnit and Mockito.",
      ],
      achievements: [],
      keywords: [
        "Java",
        "J2EE",
        "Spring Boot",
        "Spring MVC",
        "Hibernate",
        "REST APIs",
        "OAuth2",
        "JWT",
        "SQL",
        "MongoDB",
        "React.js",
        "Redux",
        "Agile",
        "Jenkins",
        "JUnit",
      ],
    },
    {
      title: "Java/J2EE Developer",
      company: "CGI Inc",
      location: "Hyderabad, India",
      startDate: "06/2019",
      endDate: "07/2022",
      duration: null,
      responsibilities: [
        "Participated in all phases of the SDLC, from requirements analysis to deployment.",
        "Developed and maintained software components using Spring MVC.",
        "Developed RESTful web services using Spring Boot.",
        "Built and managed microservices using Spring Boot.",
        "Integrated Spring Boot with Hibernate for data persistence.",
        "Used JMS for asynchronous communication.",
        "Built web applications using HTML5, CSS3, Bootstrap, and AngularJS.",
        "Developed and managed Node.js streams for data processing.",
        "Worked with EJB for business logic and deployed on WebSphere Application Server.",
        "Used XML and JAXB for data exchange.",
        "Developed SOAP and WSDL web services.",
        "Designed and executed JUnit test cases.",
        "Used Log4J for logging and debugging.",
        "Worked in an Agile SCRUM environment.",
      ],
      achievements: [],
      keywords: [
        "J2EE",
        "Spring Framework",
        "Spring MVC",
        "Spring Boot",
        "Microservices",
        "Hibernate",
        "JMS",
        "HTML5",
        "CSS3",
        "Bootstrap",
        "AngularJS",
        "Node.js",
        "RESTful services",
        "EJB",
        "WebSphere",
        "XML",
        "JAXB",
        "SOAP",
        "JUnit",
        "Agile",
        "SCRUM",
      ],
    },
  ],
  skills: {
    technical: [
      "Java",
      "Spring Boot",
      "Spring MVC",
      "Node.js",
      "React.js",
      "JavaScript",
      "HTML",
      "CSS",
      "Docker",
      "Kubernetes",
      "AWS",
      "NoSQL",
      "SQL",
      "Microservices",
      "API",
      "REST",
      "Agile",
      "Jenkins",
      "Git",
    ],
    soft: [
      "Communication",
      "Analytical Abilities",
      "Teamwork",
      "Interpersonal Skills",
    ],
    certifications: [],
    languages: [],
    categories: {},
  },
  education: [
    {
      institution: "Osmania University",
      degree: "Bachelor's",
      field: "Computer Science",
      location: null,
      graduationDate: "2020",
      gpa: null,
      honors: [],
      relevantCourses: [],
    },
    {
      institution: "Central Michigan University",
      degree: "Master's",
      field: "Information Technology",
      location: null,
      graduationDate: "2024",
      gpa: null,
      honors: [],
      relevantCourses: [],
    },
  ],
  projects: [],
  certifications: [],
  optimizationNotes: {
    keywordsAdded: [
      "Cloud",
      "Microservices",
      "API",
      "Docker",
      "Kubernetes",
      "Agile",
      "Scrum",
      "RESTful",
      "DevOps",
      "CI/CD",
    ],
    optimizationStrategy:
      "Tailored the resume to the job description by prioritizing relevant skills and experiences, enhancing bullet points with action verbs and quantifiable achievements, and incorporating keywords naturally within the context of the resume.",
    atsCompatibilityImprovements: [
      "Used consistent formatting and headings.",
      "Prioritized hard skills and technical qualifications.",
      "Simplified language and avoided jargon.",
      "Incorporated relevant keywords throughout the resume.",
    ],
    prioritizedSkills: [
      "Java",
      "Spring Boot",
      "Microservices",
      "Cloud",
      "AWS",
      "Docker",
      "Kubernetes",
      "Agile",
      "React.js",
      "Node.js",
    ],
    formattingRecommendations: [
      "Use a clean and professional font.",
      "Maintain consistent spacing and margins.",
      "Use bullet points to highlight key accomplishments and responsibilities.",
      "Save the resume in a PDF format.",
    ],
    summaryOptimizations: [
      "Condensed the summary to focus on key skills and experience relevant to the job description.",
      "Rewritten the technical summary to highlight specific technologies mentioned in the job posting.",
    ],
  },
  atsMatchScore: {
    score: 52,
    keywordsFound: 17,
    totalKeywords: 33,
  },
};
